set TRACE_CONSTRUCTION=
set TRACE_DESTRUCTION=
set TRACE_CREATION=
set TRACE_FINALIZATION=

rem set TRACE_CONSTRUCTION=-D__TRACE_CONSTRUCTION__
rem set TRACE_DESTRUCTION=-D__TRACE_DESTRUCTION__
rem set TRACE_CREATION=-D__TRACE_CREATION__
rem set TRACE_FINALIZATION=-D__TRACE_FINALIZATION__
