set TRACE_CONSTRUCTION=
set TRACE_DESTRUCTION=
set TRACE_CREATION=
set TRACE_FINALIZATION=

set TRACE_CONSTRUCTION=-D__TRACE_CONSTRUCTION__
set TRACE_DESTRUCTION=-D__TRACE_DESTRUCTION__
set TRACE_CREATION=-D__TRACE_CREATION__
set TRACE_FINALIZATION=-D__TRACE_FINALIZATION__
